spring:
  application:
    name: ecomm-user-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: learning

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
